#!/bin/bash -e

# This script is intended to run inside docker as a reproducible way to upgrade
# versions of R (also potentially install some dependencies we use)

R_SOURCE="https://cran.r-project.org/src/base/R-3/R-3.4.3.tar.gz"
BUILD_DIR="/build"
VENDOR_DIR="/home/target"

mkdir -p $BUILD_DIR

# Download the source code from CRAN
echo "Downloading R source code from $R_SOURCE"
curl $R_SOURCE -s -o - | tar xzf - -C $BUILD_DIR

cd $BUILD_DIR/R-3.4.3

./configure --prefix=/app/vendor/R \
  --enable-memory-profiling \
  --enable-R-profiling \
  --enable-R-shlib \
  --with-blas \
  --with-cairo \
  --with-jpeglib \
  --with-lapack \
  --with-readline \
  --enable-lto

make

mkdir -p $VENDOR_DIR/R/bin

cp /build/R-3.4.3/bin/R $VENDOR_DIR/R/bin/R
cp /build/R-3.4.3/bin/Rscript $VENDOR_DIR/R/bin/Rscript

mkdir -p $VENDOR_DIR/R/lib

for dir in bin doc etc include lib library modules share; do
  mkdir -p $VENDOR_DIR/R/lib/R/$dir
  cp -r /build/R-3.4.3/$dir $VENDOR_DIR/R/lib/R
done

cd /home

tar -cvzf R-3.4.3-runtime.tar.gz $VENDOR_DIR
