#!/bin/bash -e

# This script is intended to run inside docker as a reproducible way to upgrade
# versions of R (also potentially install some dependencies we use)

R_SOURCE="https://cran.r-project.org/src/base/R-3/R-3.4.3.tar.gz"
BUILD_DIR="/build"
VENDOR_DIR="/home/target"

mkdir -p $BUILD_DIR

# Download the source code from CRAN
echo "Downloading R source code from $R_SOURCE"
curl $R_SOURCE -s -o - | tar xzf - -C $BUILD_DIR

cd $BUILD_DIR/R-3.4.3

./configure --prefix=/app/vendor/R \
  --enable-memory-profiling \
  --enable-R-profiling \
  --enable-R-shlib \
  --with-blas \
  --with-cairo \
  --with-jpeglib \
  --with-lapack \
  --with-readline \
  --enable-lto

make
make install

tar -C /app/vendor/R -cvzf /home/R-3.4.3-runtime.tar.gz .
